In [60]:
import pandas as pd
import numpy as np

# 1 
Read the City Cemetery data into a pandas DataFrame.

In [61]:
NSS = pd.read_excel('../data/Historic_Nashville_City_Cemetery_Interments__1846-1979.xlsx', index_col=0)

In [67]:
NSS.head()

,Name,Burial Month,Month No.,Burial Day,Burial Year,Sex,Race,Age,Residence,Cause of Death/Burial,Ave,Section/Lot,Remarks
Volume,,,,,,,,,,,,,
6B,"Bell, Nancy Ann",Aug,8.0,6.0,1979.0,F,W,10.0,NaN,NaN,Oak,"sec. 28 NW, lot 12",J. L. Hughes lot
6W,"Drake, Mary Edith Smith, Mrs.",May,5.0,19.0,1979.0,F,W,67.0,"Madison, Tenn",Cancer,"Locust, Boyd Lot",lot 10,"wife of Alex M. Drake, Madison Funeral Home Of..."
6D,"Davis, Bessie",Sep,9.0,19.0,1979.0,F,W,90.0,Nashville,Old Age,Poplar,"McAllister, E25, lot 8",daughter of Helen Davis
6C,"Creech, Emily Green",Aug,8.0,NaN,1978.0,F,W,91.0,Nashville,NaN,sect.ion 9,15,Magnolia
6W,"Creech, Emily Green",Aug,8.0,NaN,1978.0,F,W,91.0,"Nashville, Tennessee",NaN,NaN,NaN,Malgnolia

# 2
a. Find the 10 most common (known) recorded causes of death

In [46]:
NSS['Cause of Death/Burial'].head(10)

Volume
6B        NaN
6W     Cancer
6D    Old Age
6C        NaN
6W        NaN
6W    Old Age
6W    Old Age
6W    Old Age
6W        NaN
6B        NaN
Name: Cause of Death/Burial, dtype: object

# b.

In [63]:
NSS.replace('Cholrea','Cholera', inplace=True)

In [64]:
NSS.replace('Still Born','Stillborn' , inplace=True)

In [76]:
NSS.replace('Feever','Fever',inplace=True)

In [77]:
NSS.replace('Diarherea','Diarrhea',inplace=True)

In [78]:
NSS

,Name,Burial Month,Month No.,Burial Day,Burial Year,Sex,Race,Age,Residence,Cause of Death/Burial,Ave,Section/Lot,Remarks
Volume,,,,,,,,,,,,,
6B,"Bell, Nancy Ann",Aug,8.0,6.0,1979.0,F,W,10.0,NaN,NaN,Oak,"sec. 28 NW, lot 12",J. L. Hughes lot
6W,"Drake, Mary Edith Smith, Mrs.",May,5.0,19.0,1979.0,F,W,67.0,"Madison, Tenn",Cancer,"Locust, Boyd Lot",lot 10,"wife of Alex M. Drake, Madison Funeral Home Of..."
6D,"Davis, Bessie",Sep,9.0,19.0,1979.0,F,W,90.0,Nashville,Old Age,Poplar,"McAllister, E25, lot 8",daughter of Helen Davis
6C,"Creech, Emily Green",Aug,8.0,NaN,1978.0,F,W,91.0,Nashville,NaN,sect.ion 9,15,Magnolia
6W,"Creech, Emily Green",Aug,8.0,NaN,1978.0,F,W,91.0,"Nashville, Tennessee",NaN,NaN,NaN,Malgnolia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4-1846,"Kingsley, A., Capt.",Sep,9.0,28.0,1846.0,M,W,67.0,City,Fever,Cedar,lot,superintendent of Nashville Cemetery
4-1846,infant,Sep,9.0,28.0,1846.0,M,W,NaN,City,Diarrhea,Central,lot,son of John Bateman
4-1846,"White, Lucinda",Sep,9.0,29.0,1846.0,F,W,25.0,City,Consumption,Central,200,Fees to be paid by M. Jennings
5-1881,"Higgins, Rebecca",Apr,4.0,10.0,NaN,F,W,68.0,City,Heart Disease,Cherry,lot,"box paid, grave on lot"
5-1881,"Eves, R.",Apr,4.0,25.0,NaN,M,W.,54.0,City,Heart Disease,Magnolia,lot,"box paid, grave on lot"

# c.

In [ ]:
NSS['Cause of Death/Burial']